version: '3'
services:
  redis-proxy:
    build:
      context: .
    image: redis-proxy
    ports:
      - "8001:8001"
    environment:
      - redis_hostname="redis:6379"
  redis:
    image: redis:latest
